### ISSUE TITLE
Package manager has died

### ISSUE THREAD

**Issue by ali0818** [FSecureLABS/drozer#343]
Running Drozer on Mac and while listing the 'app.package.info' getting the error "Package manager has died"

### Environment

**Operating system**: Mac 10.13.4

**Java Version:** 1.8.0_172

**Android Version:** 6.0.1

**Drozer Version:** v2.4.4

**Install Method:** source installed

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
dz> run app.package.attacksurface net.one97.paytm
exception in module: ReflectionException: Package manager has died
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/drozer/modules/app/package.py", line 29, in execute
    package = self.packageManager().getPackageInfo(arguments.package, common.PackageManager.GET_ACTIVITIES | common.PackageManager.GET_RECEIVERS | common.PackageManager.GET_PROVIDERS | common.PackageManager.GET_SERVICES)
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/drozer/modules/common/package_manager.py", line 62, in getPackageInfo
    return self.__package_manager.getPackageInfo(package, flags)
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/pydiesel/reflection/types/reflected_object.py", line 62, in _invoker
    result = self._reflector.invoke(self, method_name, *map(lambda arg: ReflectedType.fromNative(arg, reflector=self._reflector), args), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/drozer-2.4.3-py2.7.egg/pydiesel/reflection/reflector.py", line 83, in invoke
    raise ReflectionException(response.reflection_response.errormessage)
ReflectionException: Package manager has died

This is the error with only this package.

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer
