### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by famasoon** [FSecureLABS/drozer#353]
### Steps to reproduce
1. `git clone https://github.com/mwrlabs/drozer/`
2. `cd drozer`
3. `python setup.py bdist_wheel`
4. Output Error

### Expected behaviour
Start the build with the log shown below.

```sh
running bdist_wheel
running build
running build_py
running build_scripts
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
...
```

### Actual behaviour
Output the following error

```sh
$ python ./setup.py bdist_wheel
Traceback (most recent call last):
  File "./setup.py", line 132, in <module>
    version = get_version(),
  File "./setup.py", line 128, in get_version
    return subprocess.check_output(version_cmd).split('-', 1)[0]
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

### Environment

**Operating system**:

```sh
$ uname -a
Linux ubuntu 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Java Version:**

```sh
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-116.04.1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-116.04.1, mixed mode, sharing)
```

**Android Version:**

```
Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-58-generic
```

**Drozer Version:** Latest clone `2.4.3-26-g3a8e109`

**Findings**
1. To run on Linux, we need to run in shell. So we must specify `shell=True` in the argument of` subprocess.check_output`.
2. Command cannot be executed if it is list

```sh
subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 1
```

3. Executing `git describe --tags` command with check_output function inserts a space.

```sh
subprocess.CalledProcessError: Command 'g i t   d e s c r i b e   - - t a g s' returned non-zero exit status 127
```

**Comment by Yogehi** [comment]
we have a docker image for drozer now

https://hub.docker.com/r/fsecurelabs/drozer

we recommend using that

**Comment by famasoon** [comment]
Thank you for reply.
I understood.
