### ISSUE TITLE
drozer could not find or compile a required extension library.

### ISSUE THREAD

**Issue by tea9** [FSecureLABS/drozer#361]
### Steps to reproduce
1.download drozer-2.4.4-py2-none-any.whl
2. pip install drozer-2.4.4-py2-none-any.whl
3.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Environment

**Operating system**:

**Java Version:**
java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
**Android Version:**

6.0.1
**Drozer Version:** 
2.4.4
**Install Method:** Built from source/.deb/.exe/..

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
run scanner.provider.injection -a com.mwr.example.sieve
Scanning com.mwr.example.sieve...
exception in module: RuntimeError: drozer could not find or compile a required extension library.

Traceback (most recent call last):
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/scanner/provider/injection.py", line 25, in execute
    for uri in self.findAllContentUris(arguments.package_or_uri):
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 228, in findContentUris
    dex_file = self.extractFromZip("classes.dex", path, self.cacheDir())
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/zip_file.py", line 14, in extractFromZip
    ZipUtil = self.loadClass("common/ZipUtil.apk", "ZipUtil")
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/Users/shaomiao/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 51, in getClassLoader
    raise RuntimeError("drozer could not find or compile a required extension library.\n")
RuntimeError: drozer could not find or compile a required extension library.

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by tea9** [comment]
it's good

**Comment by 0x9k** [comment]
Hi,have u solve this problem?
I had the same problem. ;(

**Comment by 0x9k** [comment]
It's seems that it could not find the common/ZipUtil.apk successfully in .pyenv.
I have solved this by hardcode the ziputil.apk path in drozer_env/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py

**Comment by jauharvp** [comment]
I have the same issue when I try to do this command
@0x9k 
#run scanner.provider.finduris -a

Can you explain in detail?

**Comment by Fi5t** [comment]
@jauharvp just change `class_loader.py` as following:

```python
    def __get_source(self, source_or_relative_path, relative_to=None):
        """
        Get source, either from an apk file or passed directly.
        """
        
        source = None

        if source_or_relative_path.endswith(".apk"):
           ...
            #apk_path = os.path.join(relative_to, *source_or_relative_path.split("/"))
            apk_path = "/Users/user/.pyenv/versions/2.7.18/lib/python2.7/site-packages/drozer-2.4.2-py2.7.egg/drozer/modules/common/ZipUtil.apk"
            java_path = apk_path.replace(".apk", ".java")
            
        ....
        return source
```

But it's a terribly dirty hack 😎

**Comment by ttimasdf** [comment]
I think the question is because `.pyenv` contains `.py` string so it triggered some unnecessary branches. modify the code as follows fix the issue without hard coding anything in.

```diff
index 2ee47d7..2b38d8b 100644
--- a/src/pydiesel/reflection/utils/class_loader.py
+++ b/src/pydiesel/reflection/utils/class_loader.py
@@ -68,7 +68,7 @@ class ClassLoader(object):
         if source_or_relative_path.endswith(".apk"):
             if relative_to == None:
                 relative_to = os.path.join(os.path.dirname(__file__), "..")
-            elif relative_to.find(".py") >= 0 or relative_to.find(".pyc") >= 0:
+            elif (relative_to.find(".py") >= 0 or relative_to.find(".pyc") >= 0) and not ".pyenv" in relative_to:
                 relative_to = os.path.dirname(relative_to)
                 
             apk_path = os.path.join(relative_to, *source_or_relative_path.split("/"))
```

**Comment by tea9** [comment]
1.use  drozer console connect --debug 

dz> run app.provider.finduri com.mwr.example.sieve
Scanning com.mwr.example.sieve...
exception in module: RuntimeError: drozer could not find or compile a required extension library.

Traceback (most recent call last):
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/console/session.py", line 394, in do_run
    module.run(argv[1:])
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/base.py", line 183, in run
    result = self.execute(arguments)
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/app/provider.py", line 124, in execute
    uris = self.findAllContentUris(arguments.package)
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 206, in findAllContentUris
    uris = uris.union(self.__search_package(package))
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 316, in __search_package
    for (path, content_uris) in self.findContentUris(package.packageName):
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/provider.py", line 228, in findContentUris
    dex_file = self.extractFromZip("classes.dex", path, self.cacheDir())
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/zip_file.py", line 14, in extractFromZip
    ZipUtil = self.loadClass("common/ZipUtil.apk", "ZipUtil")
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/loader.py", line 30, in loadClass
    Module.cache_klass(".".join([source, klass]), loader.loadClass(klass))
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 28, in loadClass
    return self.getClassLoader().loadClass(klass);
  File "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py", line 51, in getClassLoader
    raise RuntimeError("drozer could not find or compile a required extension library.\n")
RuntimeError: drozer could not find or compile a required extension library.

3.open  file /Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pydiesel/reflection/utils/class_loader.py

4. just change 
Make sure the“ ZipUtil.apk” is accessible
example
apk_path = "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/ZipUtil.apk"

 def __get_source(self, source_or_relative_path, relative_to=None):
        """
        Get source, either from an apk file or passed directly.
        """
        
        source = None

        if source_or_relative_path.endswith(".apk"):
            if relative_to == None:
                relative_to = os.path.join(os.path.dirname(__file__), "..")
            elif relative_to.find(".py") >= 0 or relative_to.find(".pyc") >= 0:
                relative_to = os.path.dirname(relative_to)
                
            #apk_path = os.path.join(relative_to, *source_or_relative_path.split("/"))
          
            apk_path = "/Users/tea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/drozer/modules/common/ZipUtil.apk"
            java_path = apk_path.replace(".apk", ".java")
            
            if os.path.exists(apk_path):
                source = fs.read(apk_path)
            elif os.path.exists(java_path):
                source = ClassBuilder(java_path, self.dx_path(), self.javac_path(), self.android_path()).build()
        else:
            source = source_or_relative_path

        return source
