### ISSUE TITLE
Fuzzinozer Results [Error 3] The system cannot find the path specified: 'U:\\/fuzzinozer_results/Results_broadcast_<PackageName>

### ISSUE THREAD

**Issue by rezamnejad** [FSecureLABS/drozer#363]
### Steps to reproduce
1. execute: drozer console connect
2. execute: module install intents.fuzzinozer
3. execute: run intents.fuzzinozer -–broadcast_intent –-package_name <PackageName>

### Expected behaviour
Tell us what should happen.
Execute intents seamlessly

### Actual behaviour
Tell us what happens instead.
intents.fuzzinozer module fails with the below error:
dz> run intents.fuzzinozer --complete_test --package_name <PackageName>
Number of intents:5565120

fuzzing_intent type: fuzzing package: <PackageName> component: md5126ef4cde1f67ab094189f3f81cc0819c0.MainActivity data_uri: https://FBbKrvZxblNdHMBxDZqWoKl8kbETsvg2hejUcZiGnqY1PKBDrITj867YOa.gov category: android.intent.category.DEFAULT action: android.intent.action.MAIN flag: ACTIVITY_BROUGHT_TO_FRONT extra_type: boolean extra_key: android.intent.extra.ALARM_COUNT extra_value: True
[Error 3] The system cannot find the path specified: 'U:\\/fuzzinozer_results/Results_fuzzing_<PackageName>'

### Environment

**Operating system**:
Windows 10

**Java Version:**
Python 2.7.16

**Android Version:**
8.0.0

**Drozer Version:** 
drozer-2.4.4
drozer-agent-2.3.4.apk

**Install Method:** Built from source/.deb/.exe/..
.msi installer

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
[Error 3] The system cannot find the path specified: 'U:\\/fuzzinozer_results/Results_fuzzing_<PackageName>'

Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
dz> run intents.fuzzinozer --complete_test --package_name <PackageName>
Number of intents:5565120

fuzzing_intent type: fuzzing package: <PackageName> component: md5126ef4cde1f67ab094189f3f81cc0819c0.MainActivity data_uri: https://J3WzTrQC.com category: android.intent.category.DEFAULT action: android.intent.action.MAIN flag: ACTIVITY_BROUGHT_TO_FRONT extra_type: boolean extra_key: android.intent.extra.ALARM_COUNT extra_value: False
exception in module: WindowsError: [Error 3] The system cannot find the path specified: 'U:\\/fuzzinozer_results/Results_fuzzing_<PackageName>'
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\drozer\console\session.py", line 394, in do_run
    module.run(argv[1:])
  File "C:\Python27\Lib\site-packages\drozer\modules\base.py", line 183, in run
    result = self.execute(arguments)
  File "C:\drozer\Modules\intents\fuzzinozer.py", line 487, in execute
    reload_option, aux_num)
  File "C:\drozer\Modules\intents\fuzzinozer.py", line 580, in test_all_possible
    extra_value, device)
  File "C:\drozer\Modules\intents\fuzzinozer.py", line 675, in run_intent
    self.current_dir)
  File "C:\drozer\Modules\intents\fuzzinozer.py", line 158, in save_logcat
    os.mkdir(result_folder)
WindowsError: [Error 3] The system cannot find the path specified: 'U:\\/fuzzinozer_results/Results_fuzzing_<PackageName>'

### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```
BroadcastQueue: Permission Denial: broadcasting Intent { flg=0x10 cmp=<PackageName>/com.google.firebase.iid.FirebaseInstanceIdInternalReceiver } from com.mwr.dz (pid=24698, uid=10161) is not exported from uid 10160 due to receiver <PackageName>/com.google.firebase.iid.FirebaseInstanceIdInternalReceiver

**Comment by Yogehi** [comment]
try our docker image https://github.com/FSecureLABS/drozer/tree/develop/docker
